/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Response200 {
  message?: string;
}

export interface Response400 {
  error?: string;
  message?: string;
  statusCode?: number;
}

export interface Response401 {
  message?: string;
}

export interface Response403 {
  message?: string;
}
