/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface NameRequestBody {
  metadata?: object;
  name: string;
}

export interface NameRequestParams {
  name: string;
}

export interface NameRequestQuery {
  otherName?: string;
}
